name: py_run
on: workflow_dispatch
jobs:
  requirements:
    runs-on: ubuntu-latest
    steps:
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: install requirements
        run: |
          make install
